// This file was generated by clasp. DO NOT EDIT by hand.
// Top-level `var` declaration: https://esbuild.github.io/faq/#top-level-var

(() => {
})();

// Copyright @debiru_R from https://github.com/debiru/clasp
